export const INIT_TRANSACTION_REQUEST = "INIT_TRANSACTION_REQUEST";
export const INIT_TRANSACTION_SUCCESS = "INIT_TRANSACTION_SUCCESS";
export const INIT_TRANSACTION_FAILURE = "INIT_TRANSACTION_FAILURE";
export const INIT_TRANSACTION_WAIT_BLOCKCHAIN_CONFIRM =
  "INIT_TRANSACTION_WAIT_BLOCKCHAIN_CONFIRM";
