export const CANCEL_SALE_REQUEST = "CANCEL_SALE_REQUEST";
export const CANCEL_SALE_REQUEST_SUCCESS = "CANCEL_SALE_REQUEST_SUCCESS";
export const CANCEL_SALE_REQUEST_FAILURE = "CANCEL_SALE_REQUEST_FAILURE";
