export const FETCH_TRANSACTION_REQUEST = "FETCH_TRANSACTION_REQUEST";
export const FETCH_TRANSACTION_SUCCESS = "FETCH_TRANSACTION_SUCCESS";
export const FETCH_TRANSACTION_FAILURE = "FETCH_TRANSACTION_FAILUE";

export const FETCH_TRADING_PROPERTY_REQUEST = "FETCH_TRADING_PROPERTY_REQUEST";
export const FETCH_TRADING_PROPERTY_SUCCESS = "FETCH_TRADING_PROPERTY_SUCCESS";
export const FETCH_TRADING_PROPERTY_FAILURE = "FETCH_TRADING_PROPERTY_FAILURE";

export const PAYMENT_REQUEST = "PAYMENT_REQUEST";
export const PAYMENT_WAIT_BLOCKCHAIN_CONFIRM =
  "PAYMENT_WAIT_BLOCKCHAIN_CONFIRM";
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
export const PAYMENT_FAILURE = "PAYMENT_FAILURE";

export const ACCEPT_TRANSACTION_REQUEST = "ACCEPT_TRANSACTION_REQUEST";
export const ACCEPT_TRANSACTION_WAIT_BLOCKCHAIN_CONFIRM =
  "ACCEPT_TRANSACTION_WAIT_BLOCKCHAIN_CONFIRM";
export const ACCEPT_TRANSACTION_SUCCESS = "ACCEPT_TRANSACTION_SUCCESS";
export const ACCEPT_TRANSACTION_FAILURE = "ACCEPT_TRANSACTION_FAILURE";

export const CONFIRM_TRANSACTION_REQUEST = "CONFIRM_TRANSACTION_REQUEST";
export const CONFIRM_TRANSACTION_WAIT_BLOCKCHAIN_CONFIRM =
  "CONFIRM_TRANSACTION_WAIT_BLOCKCHAIN_CONFIRM";
export const CONFIRM_TRANSACTION_SUCCESS = "CONFIRM_TRANSACTION_SUCCESS";
export const CONFIRM_TRANSACTION_FAILURE = "CONFIRM_TRANSACTION_FAILURE";

export const CANCEL_TRANSACTION_REQUEST = "CANCEL_TRANSACTION_REQUEST";
export const CANCEL_TRANSACTION_WAIT_BLOCKCHAIN_CONFIRM =
  "CANCEL_TRANSACTION_WAIT_BLOCKCHAIN_CONFIRM";
export const CANCEL_TRANSACTION_SUCCESS = "CANCEL_TRANSACTION_SUCCESS";
export const CANCEL_TRANSACTION_FAILURE = "CANCEL_TRANSACTION_FAILURE";
