export const FETCH_TRANSACTION_REQUEST = "FETCH_TRANSACTION_REQUEST";
export const FETCH_TRANSACTION_SUCCESS = "FETCH_TRANSACTION_SUCCESS";
export const FETCH_TRANSACTION_FAILURE = "FETCH_TRANSACTION_FAILUE";

export const FETCH_TRADING_PROPERTY_REQUEST = "FETCH_TRADING_PROPERTY_REQUEST";
export const FETCH_TRADING_PROPERTY_SUCCESS = "FETCH_TRADING_PROPERTY_SUCCESS";
export const FETCH_TRADING_PROPERTY_FAILURE = "FETCH_TRADING_PROPERTY_FAILURE";
