export const ADD_ROLE_REQUEST = "ADD_ROLE_REQUEST";
export const ADD_ROLE_WAIT_BLOCKCHAIN_CONFIRM =
  "ADD_ROLE_WAIT_BLOCKCHAIN_CONFIRM";
export const ADD_ROLE_FAILURE = "ADD_ROLE_FAILURE";

export const REMOVE_ROLE_REQUEST = "REMOVE_ROLE_REQUEST";
export const REMOVE_ROLE_WAIT_BLOCKCHAIN_CONFIRM =
  "REMOVE_ROLE_WAIT_BLOCKCHAIN_CONFIRM";
export const REMOVE_ROLE_FAILURE = "REMOVE_ROLE_FAILURE";

export const ROLE_CHANGED = "ROLE_CHANGED";
