export const FETCH_MY_LISTING_REQUEST = "FETCH_MY_LISTING_REQUEST";
export const FETCH_MY_LISTING_SUCCESS = "FETCH_MY_LISTING_SUCCESS";
export const FETCH_MY_LISTING_ERROR = "FETCH_MY_LISTING_ERROR";
