export const FETCH_MY_LISTING_REQUESTING = "FETCH_MY_LISTING_REQUESTING";
export const FETCH_MY_LISTING_SUCCESS = "FETCH_MY_LISTING_SUCCESS";
export const FETCH_MY_LISTING_ERROR = "FETCH_MY_LISTING_ERROR";
