export const ACCEPT_TRANSACTION_REQUEST = "ACCEPT_TRANSACTION_REQUEST";
export const ACCEPT_TRANSACTION_SUCCESS = "ACCEPT_TRANSACTION_SUCCESS";
export const ACCEPT_TRANSACTION_FAILURE = "ACCEPT_TRANSACTION_FAILURE";
