export const FETCH_SINGLE_PROPERTY_REQUEST = "FETCH_SINGLE_PROPERTY_REQUEST";
export const FETCH_SINGLE_PROPERTY_SUCCESS = "FETCH_SINGLE_PROPERTY_SUCCESS";
export const FETCH_SINGLE_PROPERTY_FAILURE = "FETCH_SINGLE_PROPERTY_FAILURE";
