export const ACTIVATE_CERTIFICATE_REQUEST = "ACTIVATE_CERTIFICATE_REQUEST";
export const ACTIVATE_CERT_WAIT_BLOCKCHAIN_CONFIRM =
  "ACTIVATE_CERT_WAIT_BLOCKCHAIN_CONFIRM";
export const ACTIVATE_CERTIFICATE_SUCCESS = "ACTIVATE_CERTIFICATE_SUCCESS";
export const ACTIVATE_CERTIFICATE_FAILURE = "ACTIVATE_CERTIFICATE_FAILURE";
