export const FILLING_FORM = "FILLING_FORM";
export const CREATE_REQUESTING = "CREATE_REQUESTING";
export const CREATE_SUCCESS = "CREATE_SUCCESS";
export const CREATE_ERROR = "CREATE_ERROR";
export const CREATE_CERT_WAIT_BLOCKCHAIN_CONFIRM =
  "CREATE_CERT_WAIT_BLOCKCHAIN_CONFIRM";
