export const FETCH_LISTINGS_SALE = "FETCH_LISTINGS_SALE";
export const FETCH_LISTINGS_SALE_SUCCESS = "FETCH_LISTINGS_SALE_SUCCESS";
export const FETCH_LISTINGS_SALE_ERROR = "FETCH_LISTINGS_SALE_ERROR";
