export const CONFIRM_TRANSACTION_REQUEST = "CONFIRM_TRANSACTION_REQUEST";
export const CONFIRM_TRANSACTION_SUCCESS = "CONFIRM_TRANSACTION_SUCCESS";
export const CONFIRM_TRANSACTION_FAILURE = "CONFIRM_TRANSACTION_FAILURE";
